name: Deploy Violin Folder

on:
  workflow_dispatch:  # ğŸ‘‰ æ‰‹å‹•è§¸ç™¼ç”¨

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Violin audio to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./audio/Violin
          destination_dir: audio/Violin
          force_orphan: true  # âœ… åŠ é€™è¡Œè§£æ±º push å¤±æ•—å•é¡Œ
