name: Deploy Violin Folder

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Violin audio to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TIMBRE }}  # ğŸ‘ˆ ä½ è¨­å®šçš„ secret åç¨±
          publish_dir: ./audio/Violin
          destination_dir: audio/Violin
          target_branch: gh-pages               # âœ… é—œéµè¡Œ
          force_orphan: true
